# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: adovmss

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      i=1
      while [ $i -le 100 ]
      do
          echo $i
          i=`expr $i + 1`
      done

- script: |
    echo Add other tasks to build, test, and deploy your project.
  displayName: 'Run a multi-line script'
